/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitRouteImport } from './routes/kit'
import { Route as PetitionRouteImport } from './routes/petition'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as StackRouteImport } from './routes/stack'
import { Route as LanesIndexRouteImport } from './routes/lanes/index'
import { Route as LanesLaneRouteImport } from './routes/lanes/$lane'
import { Route as StatesIndexRouteImport } from './routes/states/index'
import { Route as StatesCodeRouteImport } from './routes/states/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionRoute = PetitionRouteImport.update({
  id: '/petition',
  path: '/petition',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesIndexRoute = LanesIndexRouteImport.update({
  id: '/lanes/',
  path: '/lanes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesLaneRoute = LanesLaneRouteImport.update({
  id: '/lanes/$lane',
  path: '/lanes/$lane',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesIndexRoute = StatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesCodeRoute = StatesCodeRouteImport.update({
  id: '/states/$code',
  path: '/states/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/petition': typeof PetitionRoute
  '/sources': typeof SourcesRoute
  '/stack': typeof StackRoute
  '/lanes/$lane': typeof LanesLaneRoute
  '/states/$code': typeof StatesCodeRoute
  '/lanes/': typeof LanesIndexRoute
  '/states/': typeof StatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/petition': typeof PetitionRoute
  '/sources': typeof SourcesRoute
  '/stack': typeof StackRoute
  '/lanes/$lane': typeof LanesLaneRoute
  '/states/$code': typeof StatesCodeRoute
  '/lanes': typeof LanesIndexRoute
  '/states': typeof StatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kit': typeof KitRoute
  '/petition': typeof PetitionRoute
  '/sources': typeof SourcesRoute
  '/stack': typeof StackRoute
  '/lanes/$lane': typeof LanesLaneRoute
  '/states/$code': typeof StatesCodeRoute
  '/lanes/': typeof LanesIndexRoute
  '/states/': typeof StatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kit'
    | '/petition'
    | '/sources'
    | '/stack'
    | '/lanes/$lane'
    | '/states/$code'
    | '/lanes/'
    | '/states/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kit'
    | '/petition'
    | '/sources'
    | '/stack'
    | '/lanes/$lane'
    | '/states/$code'
    | '/lanes'
    | '/states'
  id:
    | '__root__'
    | '/'
    | '/kit'
    | '/petition'
    | '/sources'
    | '/stack'
    | '/lanes/$lane'
    | '/states/$code'
    | '/lanes/'
    | '/states/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitRoute: typeof KitRoute
  PetitionRoute: typeof PetitionRoute
  SourcesRoute: typeof SourcesRoute
  StackRoute: typeof StackRoute
  LanesLaneRoute: typeof LanesLaneRoute
  StatesCodeRoute: typeof StatesCodeRoute
  LanesIndexRoute: typeof LanesIndexRoute
  StatesIndexRoute: typeof StatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petition': {
      id: '/petition'
      path: '/petition'
      fullPath: '/petition'
      preLoaderRoute: typeof PetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/': {
      id: '/lanes/'
      path: '/lanes'
      fullPath: '/lanes/'
      preLoaderRoute: typeof LanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/$lane': {
      id: '/lanes/$lane'
      path: '/lanes/$lane'
      fullPath: '/lanes/$lane'
      preLoaderRoute: typeof LanesLaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/': {
      id: '/states/'
      path: '/states'
      fullPath: '/states/'
      preLoaderRoute: typeof StatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$code': {
      id: '/states/$code'
      path: '/states/$code'
      fullPath: '/states/$code'
      preLoaderRoute: typeof StatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitRoute: KitRoute,
  PetitionRoute: PetitionRoute,
  SourcesRoute: SourcesRoute,
  StackRoute: StackRoute,
  LanesLaneRoute: LanesLaneRoute,
  StatesCodeRoute: StatesCodeRoute,
  LanesIndexRoute: LanesIndexRoute,
  StatesIndexRoute: StatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
